server:
  port: 8081

spring:
  datasource:
    username: eledevo
    password: eledevo@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://100.67.168.11:3305/vks-db
app:
  host: http://100.113.61.3:9000