server:
  port: 8081

spring:
  datasource:
    username: eledevo
    password: eledevo@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.7:3306/vks-db
  jackson:
    default-property-inclusion: non_null
  mvc:
    log-resolved-exception: on
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

application:
  security:
    jwt:
      secret-key: B3pSB4hhA4ApRtJQVv/FXoKwsCKZtNQ3CM81G0sPS0tQ+eLsW+6W/EZwE2oEahQK
      expiration: 86400000
      refresh-token:
        expiration: 604800000