server:
  port: 8081  # Mặc định cho local

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  jackson:
    default-property-inclusion: non_null
  mvc:
    log-resolved-exception: on
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

application:
  security:
    jwt:
      secret-key: B3pSB4hhA4ApRtJQVv/FXoKwsCKZtNQ3CM81G0sPS0tQ+eLsW+6W/EZwE2oEahQK
      expiration: 86400000
      refresh-token:
        expiration: 604800000

file:
  upload-dir: src/main/resources/storage

# Cấu hình cho từng môi trường
---
spring:
  profiles: local
  datasource:
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vks-db  # Cấu hình cho local
  app:
    host: http://localhost:8081

---
spring:
  profiles: dev
  datasource:
    username: eledevo
    password: eledevo@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://100.67.168.11:3306/vks-db  # Cấu hình cho dev
  app:
    host: http://100.67.168.11:8081

---
spring:
  profiles: test
  datasource:
    username: tester
    password: eledevo@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://100.67.168.11:3307/test-db  # Cấu hình cho test
  app:
    host: http://100.67.168.11:8082
