spring:
  profiles:
    active: dev
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: false
  jackson:
    default-property-inclusion: non_null
  mvc:
    log-resolved-exception: on
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
application:
  security:
    jwt:
      secret-key: B3pSB4hhA4ApRtJQVv/FXoKwsCKZtNQ3CM81G0sPS0tQ+eLsW+6W/EZwE2oEahQK
      expiration: 86400000
      refresh-token:
        expiration: 604800000

minio:
  url: http://100.113.61.3:9000            # URL của MinIO server (thay bằng địa chỉ và cổng của server)
  access-key: admin                 # Access key của MinIO
  secret-key: admin12345             # Secret key của MinIO
  bucket-name: vks-store                 # Tên bucket mặc định trong MinIO để lưu trữ
  secure: false